import pandas as pd
import numpy as np
import re
import os
from pathlib import Path

from Portal_ML_V4.src.config.settings import PROCESSED_DATA_DIR, DB_CONNECTION_STRING
from Portal_ML_V4.src.utils.name_cleaner import resolve_best_name
from Portal_ML_V4.src.utils.phone import normalize_phone, clean_id_excel_safe

# ==========================================
# 1. CONFIGURATION
# ==========================================

# Input paths (generated by upstream pipeline steps)
POS_CLIENT_SUMMARY_PATH  = PROCESSED_DATA_DIR / "pos_data"     / "pos_dim_clients.csv"
POS_ITEM_HISTORY_PATH    = PROCESSED_DATA_DIR / "pos_data"     / "pos_client_item_history.csv"
WEBSITE_CLIENT_PATH      = PROCESSED_DATA_DIR / "website_data" / "website_dim_clients.csv"
WEBSITE_ITEM_PATH        = PROCESSED_DATA_DIR / "website_data" / "website_item_history.csv"
WEBSITE_LINEITEMS_PATH   = PROCESSED_DATA_DIR / "website_data" / "website_fact_lineitems.csv"  # one row per order line

# Social media purchases come from analytics.py output
SOCIAL_PURCHASES_PATH    = PROCESSED_DATA_DIR / "fact_product_mentions.csv"
SESSIONS_PATH            = PROCESSED_DATA_DIR / "fact_sessions_enriched.csv"
RFV_PATH                 = PROCESSED_DATA_DIR / "dim_customers_rfv.csv"

OUTPUT_PATH = PROCESSED_DATA_DIR / "Portal_Client_List.xlsx"

# Tier thresholds (applied consistently across all channels)
TIER_THRESHOLDS = {
    "Platinum": 20000,
    "Gold":     13000,
    "Silver":   7000,
    "Bronze":   0,
}

# Channel name mapping (matches CHANNEL_MAP in analytics.py)
CHANNEL_MAP = {
    389017: 'WhatsApp',
    387986: 'Instagram',
    388255: 'Facebook',
    388267: 'TikTok',
    389086: 'Web Chat'
}

SOCIAL_CHANNELS = {'WhatsApp', 'Instagram', 'Facebook', 'TikTok', 'Web Chat'}

# ==========================================
# 2. SHARED HELPERS
# ==========================================

# Strip illegal Excel characters before writing
# _xNNNN_ text sequences get re-encoded by openpyxl as actual control chars on write
_XESCAPE_RE = re.compile(r'_x[0-9A-Fa-f]{4}_')


def sanitize_for_excel(df):
    # Applied to every cell regardless of dtype.
    # Handles _x001F_ text escapes AND real embedded control chars.
    def _clean(val):
        if val is None:
            return None
        if not isinstance(val, str):
            return val
        val = _XESCAPE_RE.sub('', val)
        val = ''.join(c for c in val if ord(c) >= 32 or c in '\t\n\r')
        val = val.strip()
        return val if val and val != 'nan' else None

    return df.apply(lambda col: col.map(_clean))





def assign_tier(spend):
    """
    Single tier function used for all channels.
    Platinum > 20k | Gold 13k-20k | Silver 7k-13k | Bronze 0-7k | No Spend <= 0
    """
    if pd.isna(spend) or spend <= 0:
        return "No Spend"
    if spend > TIER_THRESHOLDS["Platinum"]:
        return "Platinum"
    if spend > TIER_THRESHOLDS["Gold"]:
        return "Gold"
    if spend > TIER_THRESHOLDS["Silver"]:
        return "Silver"
    return "Bronze"


# ==========================================
# 3. LOAD EACH SOURCE
# ==========================================

def load_online_clients(engine=None):
    """
    Loads online (social media / chat) clients from analytics pipeline outputs.
    Source: dim_customers_rfv.csv (RFM stats) joined to fact_sessions_enriched.csv
    (channel + spend detail). No DB table exists for online clients.
    """
    print("   🌐 Loading online clients from analytics outputs...")

    if not RFV_PATH.exists():
        print(f"      ⚠️  Not found: {RFV_PATH.name}. Run analytics.py first.")
        return pd.DataFrame()

    df = pd.read_csv(RFV_PATH)
    print(f"      ✅ {len(df):,} online client records loaded.")

    # Enrich with channel info from sessions if available
    if SESSIONS_PATH.exists():
        sess = pd.read_csv(SESSIONS_PATH, usecols=lambda c: c in [
            'Contact ID', 'channel_name', 'contact_name', 'phone_number'
        ])
        sess['Contact ID'] = sess['Contact ID'].astype(str).str.strip()
        df['Contact ID']   = df['Contact ID'].astype(str).str.strip()
        df = df.merge(sess.drop_duplicates('Contact ID'), on='Contact ID', how='left')

    # --- Name cleanup ---
    if 'client_name' in df.columns:
        name_audit_col = 'name_audit_flag' if 'name_audit_flag' in df.columns else None
        df['client_name'] = df.apply(
            lambda r: resolve_best_name(
                r['client_name'],
                r[name_audit_col] if name_audit_col else None
            ),
            axis=1
        )

    # --- Phone normalisation (DB stores raw values) ---
    phone_col = next((c for c in df.columns if 'phone' in c.lower()), None)
    if phone_col:
        df['phone_clean'] = df[phone_col].apply(normalize_phone)
    else:
        df['phone_clean'] = None

    # --- Map channel ID -> channel name for primary_source ---
    channel_col = next((c for c in df.columns if 'channel' in c.lower()), None)
    if channel_col:
        df['primary_source'] = (
            pd.to_numeric(df[channel_col], errors='coerce')
            .map(CHANNEL_MAP)
            .fillna("WhatsApp")
        )
    else:
        df['primary_source'] = 'WhatsApp'

    # --- Spend column (already calculated by analytics.py) ---
    spend_col = next(
        (c for c in ['monetary_value', 'total_spend', 'mpesa_amount'] if c in df.columns),
        None
    )
    df['whatsapp_spend'] = pd.to_numeric(df[spend_col], errors='coerce').fillna(0) if spend_col else 0
    df['pos_spend']      = 0.0
    df['website_spend']  = 0.0

    df['channel_tier'] = df['whatsapp_spend'].apply(assign_tier)

    return df


def load_pos_clients(engine=None):
    """
    Loads physical walk-in clients.
    Primary: reads from mv_client_list in Postgres (source of truth).
    Fallback: reads from pos_dim_clients.csv if DB unavailable.
    """
    print("   🏪 Loading POS walk-in clients...")

    # Try DB first
    if engine is not None:
        try:
            df = pd.read_sql(
                "SELECT * FROM mv_client_list",
                engine
            )
            print(f"      ✅ {len(df):,} POS clients loaded from DB.")
        except Exception as e:
            print(f"      ⚠️  DB load failed ({e}), falling back to CSV...")
            df = pd.DataFrame()
    else:
        df = pd.DataFrame()

    # CSV fallback
    if df.empty:
        if not POS_CLIENT_SUMMARY_PATH.exists():
            print(f"      ⚠️  No POS data available (DB unavailable and CSV not found).")
            return pd.DataFrame(), pd.DataFrame()
        df = pd.read_csv(POS_CLIENT_SUMMARY_PATH)
        print(f"      ✅ {len(df):,} POS clients loaded from CSV.")

    phone_col = next((c for c in df.columns if 'phone' in c.lower()), None)
    if phone_col:
        df['phone_clean'] = df[phone_col].apply(normalize_phone)
    else:
        df['phone_clean'] = None

    spend_col = next((c for c in ['Total_Spend', 'total_spend'] if c in df.columns), None)
    df['pos_spend']      = pd.to_numeric(df[spend_col], errors='coerce').fillna(0) if spend_col else 0
    df['whatsapp_spend'] = 0.0
    df['website_spend']  = 0.0

    df['primary_source'] = 'Walk-In'
    df['channel_tier']   = df['pos_spend'].apply(assign_tier)

    name_col = next((c for c in ['Client Name', 'client_name'] if c in df.columns), None)
    if name_col and name_col != 'client_name':
        df = df.rename(columns={name_col: 'client_name'})

    df_items = pd.DataFrame()
    if POS_ITEM_HISTORY_PATH.exists():
        df_items = pd.read_csv(POS_ITEM_HISTORY_PATH)
        phone_col_items = next((c for c in df_items.columns if 'phone' in c.lower()), None)
        if phone_col_items:
            df_items['phone_clean'] = df_items[phone_col_items].apply(normalize_phone)
        df_items['source'] = 'Walk-In'

    return df, df_items


def load_website_clients():
    """
    Loads website order clients.
    Returns:
      df       — one row per client (from website_dim_clients.csv)
      df_items — one row per order line with order_date intact (from website_fact_lineitems.csv)
                 Falls back to aggregated website_item_history.csv if lineitems not found.
    """
    print("   🌍 Loading website clients...")
    if not WEBSITE_CLIENT_PATH.exists():
        print(f"      ⚠️  Not found: {WEBSITE_CLIENT_PATH}. Run website_orders.py first.")
        return pd.DataFrame(), pd.DataFrame()

    df = pd.read_csv(WEBSITE_CLIENT_PATH)
    print(f"      ✅ {len(df):,} website clients loaded.")

    phone_col = next((c for c in ['phone_clean', 'phone_number'] if c in df.columns), None)
    if phone_col:
        # Strip leading 00 international prefix (e.g. 0025472... → +25472...)
        # before passing to normalize_phone, which expects +254 or 07XX format
        def _normalize_web_phone(val):
            if pd.isna(val):
                return None
            s = str(val).strip()
            if s.startswith('00'):
                s = '+' + s[2:]
            return normalize_phone(s)
        df['phone_clean'] = df[phone_col].apply(_normalize_web_phone)
    else:
        df['phone_clean'] = None

    spend_col = next((c for c in ['Total_Spend', 'total_spend'] if c in df.columns), None)
    df['website_spend']  = pd.to_numeric(df[spend_col], errors='coerce').fillna(0) if spend_col else 0
    df['whatsapp_spend'] = 0.0
    df['pos_spend']      = 0.0

    df['primary_source'] = 'Website Order'
    df['channel_tier']   = df['website_spend'].apply(assign_tier)

    name_col = next((c for c in ['client_name', 'Client Name'] if c in df.columns), None)
    if name_col and name_col != 'client_name':
        df = df.rename(columns={name_col: 'client_name'})

    # Prefer fact lineitems (one row per order line, order_date intact)
    # Fall back to aggregated item history if the new file hasn't been generated yet
    df_items = pd.DataFrame()
    if WEBSITE_LINEITEMS_PATH.exists():
        df_items = pd.read_csv(WEBSITE_LINEITEMS_PATH)
        df_items['order_date'] = pd.to_datetime(df_items['order_date'], errors='coerce')
        df_items['source'] = 'Website'
        print(f"      ✅ {len(df_items):,} website line-item rows loaded (fact lineitems).")
    elif WEBSITE_ITEM_PATH.exists():
        df_items = pd.read_csv(WEBSITE_ITEM_PATH)
        df_items['source'] = 'Website'
        print(f"      ⚠️  Fact lineitems not found — using aggregated item history.")
        print(f"           Run website_orders.py to generate website_fact_lineitems.csv")

    return df, df_items


def load_social_media_purchases():
    """
    Loads confirmed social media purchases from analytics.py output.

    fact_product_mentions.csv  — one row per product per session (with revenue)
    fact_sessions_enriched.csv — used to pull channel name per session

    Only includes sessions where is_converted = 1 (actual purchases).
    """
    print("   📱 Loading social media purchases...")

    if not SOCIAL_PURCHASES_PATH.exists():
        print(f"      ⚠️  Not found: {SOCIAL_PURCHASES_PATH}. Run analytics.py first.")
        return pd.DataFrame()

    df = pd.read_csv(SOCIAL_PURCHASES_PATH)

    # Only real purchases
    df = df[df['is_converted'] == 1].copy()

    if df.empty:
        print("      ⚠️  No converted social media purchases found.")
        return pd.DataFrame()

    # Normalise phone
    df['phone_clean'] = df['Contact ID'].apply(normalize_phone)

    # Pull channel name from sessions so we know WhatsApp vs Instagram etc.
    if SESSIONS_PATH.exists():
        df_sess = pd.read_csv(
            SESSIONS_PATH,
            usecols=lambda c: c in ['Contact ID', 'channel_name', 'session_id', 'contact_name']
        )
        df = pd.merge(df, df_sess, on=['Contact ID', 'session_id'], how='left')

    # Map to source label
    if 'channel_name' in df.columns:
        df['source'] = df['channel_name'].where(
            df['channel_name'].isin(SOCIAL_CHANNELS), other='WhatsApp'
        )
    else:
        df['source'] = 'WhatsApp'

    # Pull client name from sessions if available
    if 'contact_name' in df.columns:
        df['client_name'] = df['contact_name']

    # Standardise column names for the unified product sheet
    rename_map = {}
    if 'product_name' in df.columns:  rename_map['product_name']  = 'Product'
    if 'brand_name'   in df.columns:  rename_map['brand_name']    = 'Brand'
    if 'category'     in df.columns:  rename_map['category']      = 'Category'
    if 'sub_category' in df.columns:  rename_map['sub_category']  = 'Sub_Category'
    if 'revenue'      in df.columns:  rename_map['revenue']       = 'Amount_Paid'
    if 'date'         in df.columns:  rename_map['date']          = 'Purchase_Date'
    df = df.rename(columns=rename_map)

    print(f"      ✅ {len(df):,} social media purchase rows loaded.")
    return df


# ==========================================
# 4. BUILD UNIFIED PRODUCT-LEVEL SHEET
# ==========================================

def build_all_clients_product_level(df_pos_items, df_website_items, df_social):
    """
    Combines product purchase history across all three channels into
    one sheet — one row per client per product per purchase.

    Columns:
      phone_clean | client_name | source | Product | Brand | Category |
      Sub_Category | Qty | Amount_Paid | Purchase_Date | All_Purchase_Dates | Location
    """
    print("\n   📦 Building unified product-level sheet...")
    frames = []

    # --- POS items ---
    if not df_pos_items.empty:
        pos = df_pos_items.copy()
        col_map = {
            'Description':        'Product',
            'Total_Spend':        'Amount_Paid',
            'Total_Qty_Bought':   'Qty',
            'All_Purchase_Dates': 'All_Purchase_Dates',
            'Last_Purchase':      'Purchase_Date',
            'Client Name':        'client_name',
        }
        pos = pos.rename(columns={k: v for k, v in col_map.items() if k in pos.columns})
        if 'source' not in pos.columns:
            pos['source'] = 'Walk-In'
        frames.append(pos)

    # --- Website items ---
    if not df_website_items.empty:
        web = df_website_items.copy()
        col_map = {
            'product_bought':   'Product',
            'Total_Spend':      'Amount_Paid',
            'Total_Qty':        'Qty',
            'All_Order_Dates':  'All_Purchase_Dates',
            'Last_Order_Date':  'Purchase_Date',
        }
        web = web.rename(columns={k: v for k, v in col_map.items() if k in web.columns})
        if 'source' not in web.columns:
            web['source'] = 'Website Order'
        frames.append(web)

    # --- Social media items ---
    if not df_social.empty:
        soc = df_social.copy()
        # analytics tracks mentions not quantities — mark clearly
        if 'Qty' not in soc.columns:
            soc['Qty'] = None
        if 'All_Purchase_Dates' not in soc.columns and 'Purchase_Date' in soc.columns:
            soc['All_Purchase_Dates'] = soc['Purchase_Date'].astype(str)
        frames.append(soc)

    if not frames:
        print("      ⚠️  No product-level data available.")
        return pd.DataFrame()

    combined = pd.concat(frames, ignore_index=True)

    # Final column order
    final_cols = [
        'phone_clean', 'client_name', 'email',
        'source',
        'Product', 'Brand', 'Category', 'Sub_Category',
        'Qty', 'Amount_Paid',
        'Purchase_Date', 'All_Purchase_Dates',
        'Location',
    ]
    final_cols = [c for c in final_cols if c in combined.columns]
    combined = combined[final_cols].sort_values(
        ['phone_clean', 'Purchase_Date'],
        ascending=[True, False],
        na_position='last'
    )

    print(f"      ✅ Product-level sheet: {len(combined):,} rows across all channels")
    return combined


# ==========================================
# 5. BUILD UNIFIED CLIENT LIST (one row per person)
# ==========================================

def build_unified_client_list(df_online, df_pos, df_website):
    """
    Merges all three sources by phone number.
    Returns one row per unique client with spend breakdown and tiers.
    """
    print("\n   🔗 Building unified client list...")

    frames = []

    KEEP_COLS = [
        'phone_clean', 'client_name', 'email',
        'primary_source', 'channel_tier',
        'whatsapp_spend', 'pos_spend', 'website_spend',
        'Total_Orders', 'total_orders', 'Total_Transactions',
        'First_Visit', 'Last_Visit', 'First_Order', 'Last_Order',
        'first_seen', 'last_seen',
        'Products_Bought', 'Branches_Visited',
        'lifetime_tier', 'lifetime_bracket'
    ]

    for df in [df_online, df_pos, df_website]:
        if df.empty:
            continue
        available = [c for c in KEEP_COLS if c in df.columns]
        frames.append(df[available].copy())

    if not frames:
        print("      ❌ No data from any source.")
        return pd.DataFrame()

    stacked = pd.concat(frames, ignore_index=True)
    stacked = stacked[stacked['phone_clean'].notna() & (stacked['phone_clean'] != '')]

    # Ensure optional columns always exist so the agg guards work reliably
    for _col in ['Branches_Visited', 'Products_Bought', 'channel_tier',
                 'whatsapp_spend', 'pos_spend', 'website_spend']:
        if _col not in stacked.columns:
            stacked[_col] = None

    def first_valid(series):
        for val in series:
            if pd.notna(val) and str(val).strip() not in ('', 'Unknown', 'nan'):
                return val
        return None

    def pipe_join_unique(series):
        vals = series.dropna().astype(str).str.strip()
        vals = vals[vals != ''].unique()
        return ' | '.join(sorted(vals)) if len(vals) > 0 else None

    # Base aggregations — always present
    agg_rules = {
        'client_name':    ('client_name',    first_valid),
        'email':          ('email',          first_valid),
        'primary_source': ('primary_source', first_valid),
        'all_channels':   ('primary_source', pipe_join_unique),
        'whatsapp_spend': ('whatsapp_spend', 'sum'),
        'pos_spend':      ('pos_spend',      'sum'),
        'website_spend':  ('website_spend',  'sum'),
    }
    # Optional columns — only include if present after stacking
    if 'Branches_Visited' in stacked.columns:
        agg_rules['Branches_Visited'] = ('Branches_Visited', first_valid)
    if 'Products_Bought' in stacked.columns:
        agg_rules['Products_Bought']  = ('Products_Bought',  pipe_join_unique)

    agg = stacked.groupby('phone_clean', as_index=False).agg(**agg_rules)

    # Primary source = highest-spend channel
    def resolve_primary_source(row):
        candidates = {
            'WhatsApp':      row['whatsapp_spend'],
            'Website Order': row['website_spend'],
            'Walk-In':       row['pos_spend'],
        }
        return max(candidates, key=candidates.get)

    agg['primary_source'] = agg.apply(resolve_primary_source, axis=1)

    # Spend totals and tiers
    agg['combined_spend'] = agg['whatsapp_spend'] + agg['pos_spend'] + agg['website_spend']
    agg['combined_tier']  = agg['combined_spend'].apply(assign_tier)
    agg['whatsapp_tier']  = agg['whatsapp_spend'].apply(assign_tier)
    agg['pos_tier']       = agg['pos_spend'].apply(assign_tier)
    agg['website_tier']   = agg['website_spend'].apply(assign_tier)

    # Multi-channel flag
    channel_count = (
        (agg['whatsapp_spend'] > 0).astype(int) +
        (agg['pos_spend']      > 0).astype(int) +
        (agg['website_spend']  > 0).astype(int)
    )
    agg['is_multichannel'] = (channel_count > 1).map({True: 'Yes', False: 'No'})

    final_cols = [
        'phone_clean', 'client_name', 'email',
        'primary_source', 'all_channels', 'is_multichannel',
        'combined_tier',  'combined_spend',
        'whatsapp_spend', 'whatsapp_tier',
        'pos_spend',      'pos_tier',
        'website_spend',  'website_tier',
        'Branches_Visited', 'Products_Bought',
    ]
    final_cols = [c for c in final_cols if c in agg.columns]
    agg = agg[final_cols].sort_values('combined_spend', ascending=False)

    print(f"      ✅ Unified list: {len(agg):,} unique clients")
    print(f"      🔀 Multi-channel clients: {(agg['is_multichannel'] == 'Yes').sum():,}")

    return agg


# ==========================================
# 6. MAIN EXPORT
# ==========================================

def run_client_export():
    print("\n" + "="*60)
    print("📋 PORTAL CLIENT LIST EXPORT")
    print("="*60)

    os.makedirs(OUTPUT_PATH.parent, exist_ok=True)

    # ── 1. Connect to DB ─────────────────────────────────────────
    engine = None
    try:
        from sqlalchemy import create_engine, text
        engine = create_engine(DB_CONNECTION_STRING)
        engine.connect()
        print("   🐘 DB connection OK")
    except Exception as e:
        print(f"   ⚠️  DB unavailable: {e}")
        engine = None

    # ── 2. Client summary from mv_client_list ────────────────────
    df_clients = pd.DataFrame()
    if engine is not None:
        try:
            df_clients = pd.read_sql("SELECT * FROM mv_client_list", engine)
            df_clients = df_clients.rename(columns={
                'phone_number':           'Phone',
                'client_name':            'Client Name',
                'preferred_location':     'Preferred Branch',
                'branches_visited':       'Branches Visited',
                'products_bought':        'Products Bought',
                'first_interaction_date': 'First Purchase',
                'last_interaction_date':  'Last Purchase',
                'total_lifetime_spend':   'Total Spend (KES)',
                'total_purchases':        'Total Transactions',
                'lifetime_tier':          'Tier',
                'name_audit_flag':        'Name Audit',
            })
            df_clients['Source'] = 'POS'
            print(f"   ✅ {len(df_clients):,} clients loaded")
        except Exception as e:
            print(f"   ❌ mv_client_list failed: {e}")

    # ── 3. Purchase history — one row per line item per transaction ──
    # Shows the actual transaction date and a visit number (1st, 2nd, 27th visit)
    # so you can see exactly when each item was bought and in which visit
    df_products = pd.DataFrame()
    if engine is not None:
        try:
            _product_sql = text("""
                WITH visit_numbers AS (
                    -- Assign a chronological visit number per client
                    -- based on distinct transaction dates
                    SELECT
                        phone_number,
                        transaction_id,
                        DENSE_RANK() OVER (
                            PARTITION BY phone_number
                            ORDER BY MIN(sale_date)
                        ) AS visit_number
                    FROM fact_sales_lineitems
                    WHERE phone_number IS NOT NULL
                      AND TRIM(phone_number) <> ''
                    GROUP BY phone_number, transaction_id
                )
                SELECT
                    f.phone_number                          AS "Phone",
                    f.client_name                           AS "Client Name",
                    f.location                              AS "Branch",
                    f.sale_date                             AS "Date",
                    v.visit_number                          AS "Visit No.",
                    f.transaction_id                        AS "Transaction ID",
                    f.description                           AS "Product",
                    f.category                              AS "Category",
                    f.department                            AS "Department",
                    f.qty_sold                              AS "Qty",
                    f.total_tax_ex                          AS "Amount (KES)",
                    CASE
                        WHEN f.ordered_via ILIKE '%whatsapp%'
                          OR f.ordered_via ILIKE '%respond%'
                        THEN 'Online / Social Media'
                        ELSE 'POS'
                    END                                     AS "Source"
                FROM fact_sales_lineitems f
                JOIN visit_numbers v
                  ON f.phone_number    = v.phone_number
                 AND f.transaction_id  = v.transaction_id
                WHERE f.phone_number IS NOT NULL
                  AND TRIM(f.phone_number) <> ''
                  AND f.description IS NOT NULL
                ORDER BY
                    f.phone_number,
                    f.sale_date DESC,
                    v.visit_number DESC,
                    f.description
            """)
            df_products = pd.read_sql(_product_sql, engine)
            print(f"   ✅ {len(df_products):,} purchase history rows loaded")
        except Exception as e:
            print(f"   ⚠️  Product detail failed: {e}")

    # ── 4. Load website data ─────────────────────────────────────
    df_website, df_website_items = load_website_clients()

    # ── 5. Merge website into All Clients (one row per person) ───
    # Strategy:
    #   - Normalize phones on both sides for matching
    #   - Clients in both  → one row, POS Spend + Website Spend shown separately
    #   - Website-only     → added as new rows, POS Spend = 0
    #   - 19 exact dupes (same phone+product+amount) excluded from website items

    # Add spend columns to POS clients
    df_clients['POS Spend (KES)']     = df_clients['Total Spend (KES)']
    df_clients['Website Spend (KES)'] = 0.0
    df_clients['phone_norm']          = df_clients['Phone'].apply(normalize_phone)

    if not df_website.empty:
        df_website['phone_norm'] = df_website['phone_clean'].apply(normalize_phone)

        phone_col_web  = 'phone_clean'
        name_col_web   = 'client_name'
        spend_col_web  = next((c for c in ['Total_Spend', 'total_spend'] if c in df_website.columns), None)

        web_spend = (
            df_website.groupby('phone_norm')[spend_col_web]
            .sum()
            .reset_index()
            .rename(columns={spend_col_web: 'web_spend'})
        ) if spend_col_web else pd.DataFrame(columns=['phone_norm', 'web_spend'])

        # Clients in BOTH — update their Website Spend
        both_mask = df_clients['phone_norm'].isin(web_spend['phone_norm'])
        df_clients = df_clients.merge(web_spend, on='phone_norm', how='left')
        df_clients.loc[both_mask, 'Website Spend (KES)'] = df_clients.loc[both_mask, 'web_spend'].fillna(0)
        df_clients = df_clients.drop(columns=['web_spend'])

        # Website-only clients — not in POS at all
        web_only_phones = set(df_website['phone_norm'].dropna()) - set(df_clients['phone_norm'].dropna())
        df_web_only = df_website[
            df_website['phone_norm'].isin(web_only_phones) |
            df_website['phone_norm'].isna()
        ].copy()

        if not df_web_only.empty:
            # website_dim_clients.csv column names (client summary, not item history)
            first_date_col  = next((c for c in ['First_Order', 'First_Order_Date',  'first_order'] if c in df_web_only.columns), None)
            last_date_col   = next((c for c in ['Last_Order',  'Last_Order_Date',   'last_order']  if c in df_web_only.columns), None)
            product_col_agg = next((c for c in ['Products_Bought', 'product_bought', 'products_bought'] if c in df_web_only.columns), None)
            txn_col         = next((c for c in ['Total_Orders', 'Times_Ordered', 'total_orders'] if c in df_web_only.columns), None)
            email_col       = next((c for c in ['email', 'Email'] if c in df_web_only.columns), None)

            # website_dim_clients has one row per client — group by phone_norm
            agg_dict = {}
            if name_col_web:     agg_dict[name_col_web]    = 'first'
            if phone_col_web:    agg_dict[phone_col_web]   = 'first'
            if email_col:        agg_dict[email_col]       = 'first'
            if product_col_agg:  agg_dict[product_col_agg] = lambda x: ' | '.join(x.dropna().astype(str).unique())
            if first_date_col:   agg_dict[first_date_col]  = 'min'
            if last_date_col:    agg_dict[last_date_col]   = 'max'
            if spend_col_web:    agg_dict[spend_col_web]   = 'sum'
            if txn_col:          agg_dict[txn_col]         = 'sum'

            df_web_only['_group_key'] = df_web_only['phone_norm'].fillna(
                df_web_only.get(name_col_web, pd.Series(dtype=str)).astype(str)
            )
            df_agg = df_web_only.groupby('_group_key', as_index=False).agg(agg_dict)

            df_web_only_fmt = pd.DataFrame({
                'Phone':               df_agg.get(phone_col_web),
                'Client Name':         df_agg.get(name_col_web),
                'Email':               df_agg[email_col] if email_col else None,
                'Preferred Branch':    'Website',
                'Branches Visited':    'Website',
                'Products Bought':     df_agg[product_col_agg] if product_col_agg else '',
                'First Purchase':      pd.to_datetime(df_agg[first_date_col], errors='coerce') if first_date_col else None,
                'Last Purchase':       pd.to_datetime(df_agg[last_date_col],  errors='coerce') if last_date_col  else None,
                'POS Spend (KES)':     None,
                'Website Spend (KES)': df_agg[spend_col_web].fillna(0) if spend_col_web else 0.0,
                'Total Transactions':  df_agg[txn_col].fillna(0).astype(int) if txn_col else None,
                'Name Audit':          '',
                'phone_norm':          df_agg['_group_key'],
            })
            df_clients = pd.concat([df_clients, df_web_only_fmt], ignore_index=True)

        print(f"   ✅ {len(web_only_phones):,} website-only clients added")
        print(f"   ✅ {both_mask.sum():,} clients updated with website spend")

    # Recalculate Total Spend and Tier from combined spend
    df_clients['Total Spend (KES)'] = (
        df_clients['POS Spend (KES)'].fillna(0) +
        df_clients['Website Spend (KES)'].fillna(0)
    )
    df_clients['Tier'] = df_clients['Total Spend (KES)'].apply(assign_tier)

    # ── Social Media Spend — check fact_sessions_enriched for confirmed purchases ──
    # Join on normalized phone to get total mpesa_amount per client
    if SESSIONS_PATH.exists():
        sess_cols = ['phone_number', 'mpesa_amount', 'is_converted']
        chunks = pd.read_csv(SESSIONS_PATH, low_memory=False, chunksize=50000)
        df_sess = pd.concat(
            [chunk[[c for c in sess_cols if c in chunk.columns]] for chunk in chunks],
            ignore_index=True
        )
        df_sess = df_sess[df_sess['is_converted'] == 1].copy()
        df_sess['phone_norm'] = df_sess['phone_number'].apply(normalize_phone)
        social_spend = (
            df_sess.groupby('phone_norm')['mpesa_amount']
            .sum()
            .reset_index()
            .rename(columns={'mpesa_amount': 'Social Media Spend (KES)'})
        )
        df_clients = df_clients.merge(social_spend, on='phone_norm', how='left')
        df_clients['Social Media Spend (KES)'] = df_clients['Social Media Spend (KES)'].fillna(0)
    else:
        df_clients['Social Media Spend (KES)'] = 0.0

    # Set Source — build from which channels have spend > 0
    has_pos    = df_clients['POS Spend (KES)'].fillna(0) > 0
    has_web    = df_clients['Website Spend (KES)'].fillna(0) > 0
    has_social = df_clients['Social Media Spend (KES)'].fillna(0) > 0

    def build_source(row):
        parts = []
        if row['_has_pos']:    parts.append('POS')
        if row['_has_web']:    parts.append('Website')
        if row['_has_social']: parts.append('Social Media')
        return ' + '.join(parts) if parts else 'POS'

    df_clients['_has_pos']    = has_pos
    df_clients['_has_web']    = has_web
    df_clients['_has_social'] = has_social
    df_clients['Source']      = df_clients.apply(build_source, axis=1)
    df_clients = df_clients.drop(columns=['_has_pos', '_has_web', '_has_social'])

    # Leave spend columns blank where there's no activity on that channel
    # (None renders as blank in Excel — cleaner than showing 0)
    df_clients.loc[~has_pos,    'POS Spend (KES)']          = None
    df_clients.loc[~has_web,    'Website Spend (KES)']       = None
    df_clients.loc[~has_social, 'Social Media Spend (KES)']  = None
    # Reorder columns so spend breakdown is clean and readable
    col_order = [
        'Client Name', 'Email', 'Phone', 'Preferred Branch', 'Branches Visited',
        'Products Bought', 'First Purchase', 'Last Purchase',
        'Total Spend (KES)', 'POS Spend (KES)', 'Website Spend (KES)', 'Social Media Spend (KES)',
        'Total Transactions', 'Tier', 'Name Audit', 'Source'
    ]
    df_clients = df_clients[[c for c in col_order if c in df_clients.columns]]

    # ── 6. Merge website items into Purchase History ──────────────
    if not df_website_items.empty and not df_products.empty:
        # Normalize phone — phone_clean column exists in fact_lineitems
        if 'phone_clean' in df_website_items.columns:
            df_website_items['phone_norm'] = df_website_items['phone_clean'].apply(normalize_phone)
        else:
            phone_col_w_items = next((c for c in df_website_items.columns if 'phone' in c.lower()), None)
            df_website_items['phone_norm'] = (
                df_website_items[phone_col_w_items].apply(normalize_phone)
                if phone_col_w_items else None
            )
        print(f"   🌐 Website items to merge : {len(df_website_items):,} rows")

        # Build duplicate fingerprint from POS side
        pos_fingerprints = set(
            zip(
                df_products['Phone'].apply(normalize_phone),
                df_products['Product'].str.upper().str.strip(),
                df_products['Amount (KES)'].round(0)
            )
        )

        product_col_w  = next((c for c in ['product_bought', 'product']            if c in df_website_items.columns), None)
        amount_col_w   = next((c for c in ['line_total', 'Total_Spend', 'amount']  if c in df_website_items.columns), None)
        qty_col_w      = next((c for c in ['quantity', 'Total_Qty', 'qty']         if c in df_website_items.columns), None)
        unit_price_col = next((c for c in ['unit_price', 'Unit_Price']             if c in df_website_items.columns), None)

        # Use order_date directly — one row per transaction line, no exploding needed
        has_order_date = 'order_date' in df_website_items.columns
        date_col_w     = 'order_date' if has_order_date else next(
            (c for c in ['First_Order_Date', 'order_date', 'date'] if c in df_website_items.columns), None
        )

        def is_pos_dupe(row):
            fp = (
                row['phone_norm'],
                str(row.get(product_col_w, '')).upper().strip(),
                round(float(row.get(amount_col_w, 0) or 0), 0)
            )
            return fp in pos_fingerprints

        dupe_mask = df_website_items.apply(is_pos_dupe, axis=1)
        df_website_items = df_website_items[~dupe_mask].copy()
        print(f"   ✅ {dupe_mask.sum():,} exact POS duplicates excluded from website items")

        # ── Assign visit numbers chronologically per phone ───────────
        df_website_items = df_website_items.sort_values(
            ['phone_norm', date_col_w] if date_col_w else ['phone_norm']
        )
        if date_col_w:
            date_ranks = (
                df_website_items[['phone_norm', date_col_w]]
                .dropna()
                .drop_duplicates()
                .copy()
            )
            date_ranks['Visit No.'] = date_ranks.groupby('phone_norm')[date_col_w].rank(
                method='dense'
            ).astype(int)
            df_website_items = df_website_items.merge(date_ranks, on=['phone_norm', date_col_w], how='left')
        else:
            df_website_items['Visit No.'] = ''

        print(f"   ✅ {len(df_website_items):,} website purchase rows remaining")

        # Format to match Purchase History columns
        df_web_hist = pd.DataFrame({
            'Phone':          df_website_items['phone_norm'],
            'Client Name':    df_website_items.get('client_name', ''),
            'Branch':         'Website',
            'Date':           df_website_items[date_col_w] if date_col_w else None,
            'Visit No.':      df_website_items.get('Visit No.', ''),
            'Transaction ID': df_website_items.get('order_id', ''),
            'Product':        df_website_items[product_col_w] if product_col_w else '',
            'Category':       df_website_items.get('category', ''),
            'Department':     df_website_items.get('department', ''),
            'Qty':            df_website_items[qty_col_w]      if qty_col_w      else '',
            'Amount (KES)':   df_website_items[unit_price_col] if unit_price_col else (
                              df_website_items[amount_col_w]   if amount_col_w   else ''),
            'Source':         'Website',
        })
        df_products = pd.concat([df_products, df_web_hist], ignore_index=True)
        print(f"   ✅ Purchase History now has {len(df_products):,} rows (POS + Website)")

    # ── 7. Tier splits ───────────────────────────────────────────
    if df_clients.empty:
        print("\n❌ No client data to export.")
        return

    def split_tier(df, tier):
        return df[df['Tier'] == tier].copy() if 'Tier' in df.columns else pd.DataFrame()

    platinum = split_tier(df_clients, 'Platinum')
    gold     = split_tier(df_clients, 'Gold')
    silver   = split_tier(df_clients, 'Silver')
    bronze   = split_tier(df_clients, 'Bronze')

    multi_channel = df_clients[df_clients['Source'] == 'POS + Website']

    print(f"\n   💎 Platinum      : {len(platinum):,}")
    print(f"   🥇 Gold          : {len(gold):,}")
    print(f"   🥈 Silver        : {len(silver):,}")
    print(f"   🥉 Bronze        : {len(bronze):,}")
    print(f"   🌐 POS + Website : {len(multi_channel):,}")
    print(f"   👥 Total         : {len(df_clients):,}")
    print(f"   📦 Products      : {len(df_products):,}")

    # ── 8. Write Excel ───────────────────────────────────────────
    print("\n   💾 Writing Excel...")
    try:
        dfs_to_clean = [df_clients, platinum, gold, silver, bronze, df_products, multi_channel]
        df_clients, platinum, gold, silver, bronze, df_products, multi_channel = (
            sanitize_for_excel(d) if not d.empty else d for d in dfs_to_clean
        )

        with pd.ExcelWriter(OUTPUT_PATH, engine='openpyxl') as writer:

            # All clients — one row per person, combined spend
            df_clients.to_excel(writer, sheet_name='All Clients', index=False)

            # Full purchase history — POS + website items combined
            if not df_products.empty:
                df_products.to_excel(writer, sheet_name='Purchase History', index=False)

            # Tier sheets
            platinum.to_excel(writer, sheet_name='Platinum', index=False)
            gold.to_excel(writer,     sheet_name='Gold',     index=False)
            silver.to_excel(writer,   sheet_name='Silver',   index=False)
            bronze.to_excel(writer,   sheet_name='Bronze',   index=False)

            # Multi-channel clients — bought both online and in store
            if not multi_channel.empty:
                multi_channel.to_excel(writer, sheet_name='POS + Website', index=False)

        print(f"\n✅ CLIENT LIST SAVED: {OUTPUT_PATH.name}")
        print(f"   Sheets:")
        print(f"      All Clients      — one row per client, POS + Website spend breakdown")
        print(f"      Purchase History — every line item, POS and website combined")
        print(f"      Platinum / Gold / Silver / Bronze — tier splits")
        print(f"      POS + Website    — clients who bought on both channels")

    except Exception as e:
        print(f"   ❌ Excel export failed: {e}")
        raise

    finally:
        if engine:
            engine.dispose()



if __name__ == "__main__":
    run_client_export()