import pandas as pd
import numpy as np
import re
import os
from pathlib import Path

from Portal_ML_V4.src.config.settings import PROCESSED_DATA_DIR, DB_CONNECTION_STRING
from Portal_ML_V4.src.utils.name_cleaner import resolve_best_name
from Portal_ML_V4.src.utils.phone import normalize_phone, clean_id_excel_safe

# ==========================================
# 1. CONFIGURATION
# ==========================================

# Input paths (generated by upstream pipeline steps)
POS_CLIENT_SUMMARY_PATH  = PROCESSED_DATA_DIR / "pos_data"     / "pos_dim_clients.csv"
POS_ITEM_HISTORY_PATH    = PROCESSED_DATA_DIR / "pos_data"     / "pos_client_item_history.csv"
WEBSITE_CLIENT_PATH      = PROCESSED_DATA_DIR / "website_data" / "website_dim_clients.csv"
WEBSITE_ITEM_PATH        = PROCESSED_DATA_DIR / "website_data" / "website_item_history.csv"

# Social media purchases come from analytics.py output
SOCIAL_PURCHASES_PATH    = PROCESSED_DATA_DIR / "fact_product_mentions.csv"
SESSIONS_PATH            = PROCESSED_DATA_DIR / "fact_sessions_enriched.csv"
RFV_PATH                 = PROCESSED_DATA_DIR / "dim_customers_rfv.csv"

OUTPUT_PATH = PROCESSED_DATA_DIR / "Portal_Client_List (updated).xlsx"

# Tier thresholds (applied consistently across all channels)
TIER_THRESHOLDS = {
    "Platinum": 20000,
    "Gold":     13000,
    "Silver":   7000,
    "Bronze":   0,
}

# Channel name mapping (matches CHANNEL_MAP in analytics.py)
CHANNEL_MAP = {
    389017: 'WhatsApp',
    387986: 'Instagram',
    388255: 'Facebook',
    388267: 'TikTok',
    389086: 'Web Chat'
}

SOCIAL_CHANNELS = {'WhatsApp', 'Instagram', 'Facebook', 'TikTok', 'Web Chat'}

# ==========================================
# 2. SHARED HELPERS
# ==========================================

# Strip illegal Excel characters before writing
# _xNNNN_ text sequences get re-encoded by openpyxl as actual control chars on write
_XESCAPE_RE = re.compile(r'_x[0-9A-Fa-f]{4}_')


def sanitize_for_excel(df):
    # Applied to every cell regardless of dtype.
    # Handles _x001F_ text escapes AND real embedded control chars.
    def _clean(val):
        if val is None:
            return None
        if not isinstance(val, str):
            return val
        val = _XESCAPE_RE.sub('', val)
        val = ''.join(c for c in val if ord(c) >= 32 or c in '\t\n\r')
        val = val.strip()
        return val if val and val != 'nan' else None

    return df.apply(lambda col: col.map(_clean))





def assign_tier(spend):
    """
    Single tier function used for all channels.
    Platinum > 20k | Gold 13k-20k | Silver 7k-13k | Bronze 0-7k | No Spend <= 0
    """
    if pd.isna(spend) or spend <= 0:
        return "No Spend"
    if spend > TIER_THRESHOLDS["Platinum"]:
        return "Platinum"
    if spend > TIER_THRESHOLDS["Gold"]:
        return "Gold"
    if spend > TIER_THRESHOLDS["Silver"]:
        return "Silver"
    return "Bronze"


# ==========================================
# 3. LOAD EACH SOURCE
# ==========================================

def load_online_clients(engine=None):
    """
    Loads online (social media / chat) clients from analytics pipeline outputs.
    Source: dim_customers_rfv.csv (RFM stats) joined to fact_sessions_enriched.csv
    (channel + spend detail). No DB table exists for online clients.
    """
    print("   🌐 Loading online clients from analytics outputs...")

    if not RFV_PATH.exists():
        print(f"      ⚠️  Not found: {RFV_PATH.name}. Run analytics.py first.")
        return pd.DataFrame()

    df = pd.read_csv(RFV_PATH)
    print(f"      ✅ {len(df):,} online client records loaded.")

    # Enrich with channel info from sessions if available
    if SESSIONS_PATH.exists():
        sess = pd.read_csv(SESSIONS_PATH, usecols=lambda c: c in [
            'Contact ID', 'channel_name', 'contact_name', 'phone_number'
        ])
        sess['Contact ID'] = sess['Contact ID'].astype(str).str.strip()
        df['Contact ID']   = df['Contact ID'].astype(str).str.strip()
        df = df.merge(sess.drop_duplicates('Contact ID'), on='Contact ID', how='left')

    # --- Name cleanup ---
    if 'client_name' in df.columns:
        name_audit_col = 'name_audit_flag' if 'name_audit_flag' in df.columns else None
        df['client_name'] = df.apply(
            lambda r: resolve_best_name(
                r['client_name'],
                r[name_audit_col] if name_audit_col else None
            ),
            axis=1
        )

    # --- Phone normalisation (DB stores raw values) ---
    phone_col = next((c for c in df.columns if 'phone' in c.lower()), None)
    if phone_col:
        df['phone_clean'] = df[phone_col].apply(normalize_phone)
    else:
        df['phone_clean'] = None

    # --- Map channel ID -> channel name for primary_source ---
    channel_col = next((c for c in df.columns if 'channel' in c.lower()), None)
    if channel_col:
        df['primary_source'] = (
            pd.to_numeric(df[channel_col], errors='coerce')
            .map(CHANNEL_MAP)
            .fillna("WhatsApp")
        )
    else:
        df['primary_source'] = 'WhatsApp'

    # --- Spend column (already calculated by analytics.py) ---
    spend_col = next(
        (c for c in ['monetary_value', 'total_spend', 'mpesa_amount'] if c in df.columns),
        None
    )
    df['whatsapp_spend'] = pd.to_numeric(df[spend_col], errors='coerce').fillna(0) if spend_col else 0
    df['pos_spend']      = 0.0
    df['website_spend']  = 0.0

    df['channel_tier'] = df['whatsapp_spend'].apply(assign_tier)

    return df


def load_pos_clients(engine=None):
    """
    Loads physical walk-in clients.
    Primary: reads from mv_client_list in Postgres (source of truth).
    Fallback: reads from pos_dim_clients.csv if DB unavailable.
    """
    print("   🏪 Loading POS walk-in clients...")

    # Try DB first
    if engine is not None:
        try:
            df = pd.read_sql(
                "SELECT * FROM mv_client_list",
                engine
            )
            print(f"      ✅ {len(df):,} POS clients loaded from DB.")
        except Exception as e:
            print(f"      ⚠️  DB load failed ({e}), falling back to CSV...")
            df = pd.DataFrame()
    else:
        df = pd.DataFrame()

    # CSV fallback
    if df.empty:
        if not POS_CLIENT_SUMMARY_PATH.exists():
            print(f"      ⚠️  No POS data available (DB unavailable and CSV not found).")
            return pd.DataFrame(), pd.DataFrame()
        df = pd.read_csv(POS_CLIENT_SUMMARY_PATH)
        print(f"      ✅ {len(df):,} POS clients loaded from CSV.")

    phone_col = next((c for c in df.columns if 'phone' in c.lower()), None)
    if phone_col:
        df['phone_clean'] = df[phone_col].apply(normalize_phone)
    else:
        df['phone_clean'] = None

    spend_col = next((c for c in ['Total_Spend', 'total_spend'] if c in df.columns), None)
    df['pos_spend']      = pd.to_numeric(df[spend_col], errors='coerce').fillna(0) if spend_col else 0
    df['whatsapp_spend'] = 0.0
    df['website_spend']  = 0.0

    df['primary_source'] = 'Walk-In'
    df['channel_tier']   = df['pos_spend'].apply(assign_tier)

    name_col = next((c for c in ['Client Name', 'client_name'] if c in df.columns), None)
    if name_col and name_col != 'client_name':
        df = df.rename(columns={name_col: 'client_name'})

    df_items = pd.DataFrame()
    if POS_ITEM_HISTORY_PATH.exists():
        df_items = pd.read_csv(POS_ITEM_HISTORY_PATH)
        phone_col_items = next((c for c in df_items.columns if 'phone' in c.lower()), None)
        if phone_col_items:
            df_items['phone_clean'] = df_items[phone_col_items].apply(normalize_phone)
        df_items['source'] = 'Walk-In'

    return df, df_items


def load_website_clients():
    """
    Loads website order clients.
    Tags source as Website Order.
    """
    print("   🌍 Loading website clients...")
    if not WEBSITE_CLIENT_PATH.exists():
        print(f"      ⚠️  Not found: {WEBSITE_CLIENT_PATH}. Run website_orders.py first.")
        return pd.DataFrame(), pd.DataFrame()

    df = pd.read_csv(WEBSITE_CLIENT_PATH)
    print(f"      ✅ {len(df):,} website clients loaded.")

    phone_col = next((c for c in ['phone_clean', 'phone_number'] if c in df.columns), None)
    if phone_col:
        df['phone_clean'] = df[phone_col].apply(normalize_phone)
    else:
        df['phone_clean'] = None

    spend_col = next((c for c in ['Total_Spend', 'total_spend'] if c in df.columns), None)
    df['website_spend']  = pd.to_numeric(df[spend_col], errors='coerce').fillna(0) if spend_col else 0
    df['whatsapp_spend'] = 0.0
    df['pos_spend']      = 0.0

    df['primary_source'] = 'Website Order'
    df['channel_tier']   = df['website_spend'].apply(assign_tier)

    name_col = next((c for c in ['client_name', 'Client Name'] if c in df.columns), None)
    if name_col and name_col != 'client_name':
        df = df.rename(columns={name_col: 'client_name'})

    df_items = pd.DataFrame()
    if WEBSITE_ITEM_PATH.exists():
        df_items = pd.read_csv(WEBSITE_ITEM_PATH)
        df_items['source'] = 'Website Order'

    return df, df_items


def load_social_media_purchases():
    """
    Loads confirmed social media purchases from analytics.py output.

    fact_product_mentions.csv  — one row per product per session (with revenue)
    fact_sessions_enriched.csv — used to pull channel name per session

    Only includes sessions where is_converted = 1 (actual purchases).
    """
    print("   📱 Loading social media purchases...")

    if not SOCIAL_PURCHASES_PATH.exists():
        print(f"      ⚠️  Not found: {SOCIAL_PURCHASES_PATH}. Run analytics.py first.")
        return pd.DataFrame()

    df = pd.read_csv(SOCIAL_PURCHASES_PATH)

    # Only real purchases
    df = df[df['is_converted'] == 1].copy()

    if df.empty:
        print("      ⚠️  No converted social media purchases found.")
        return pd.DataFrame()

    # Normalise phone
    df['phone_clean'] = df['Contact ID'].apply(normalize_phone)

    # Pull channel name from sessions so we know WhatsApp vs Instagram etc.
    if SESSIONS_PATH.exists():
        df_sess = pd.read_csv(
            SESSIONS_PATH,
            usecols=lambda c: c in ['Contact ID', 'channel_name', 'session_id', 'contact_name']
        )
        df = pd.merge(df, df_sess, on=['Contact ID', 'session_id'], how='left')

    # Map to source label
    if 'channel_name' in df.columns:
        df['source'] = df['channel_name'].where(
            df['channel_name'].isin(SOCIAL_CHANNELS), other='WhatsApp'
        )
    else:
        df['source'] = 'WhatsApp'

    # Pull client name from sessions if available
    if 'contact_name' in df.columns:
        df['client_name'] = df['contact_name']

    # Standardise column names for the unified product sheet
    rename_map = {}
    if 'product_name' in df.columns:  
        rename_map['product_name']  = 'Product'
    if 'brand_name'   in df.columns:  
        rename_map['brand_name']    = 'Brand'
    if 'category'     in df.columns:  
        rename_map['category']      = 'Category'
    if 'sub_category' in df.columns:  
        rename_map['sub_category']  = 'Sub_Category'
    if 'revenue'      in df.columns:  
        rename_map['revenue']       = 'Amount_Paid'
    if 'date'         in df.columns:  
        rename_map['date']          = 'Purchase_Date'
    df = df.rename(columns=rename_map)

    print(f"      ✅ {len(df):,} social media purchase rows loaded.")
    return df


# ==========================================
# 4. BUILD UNIFIED PRODUCT-LEVEL SHEET
# ==========================================

def build_all_clients_product_level(df_pos_items, df_website_items, df_social):
    """
    Combines product purchase history across all three channels into
    one sheet — one row per client per product per purchase.

    Columns:
      phone_clean | client_name | source | Product | Brand | Category |
      Sub_Category | Qty | Amount_Paid | Purchase_Date | All_Purchase_Dates | Location
    """
    print("\n   📦 Building unified product-level sheet...")
    frames = []

    # --- POS items ---
    if not df_pos_items.empty:
        pos = df_pos_items.copy()
        col_map = {
            'Description':        'Product',
            'Total_Spend':        'Amount_Paid',
            'Total_Qty_Bought':   'Qty',
            'All_Purchase_Dates': 'All_Purchase_Dates',
            'Last_Purchase':      'Purchase_Date',
            'Client Name':        'client_name',
        }
        pos = pos.rename(columns={k: v for k, v in col_map.items() if k in pos.columns})
        if 'source' not in pos.columns:
            pos['source'] = 'Walk-In'
        frames.append(pos)

    # --- Website items ---
    if not df_website_items.empty:
        web = df_website_items.copy()
        col_map = {
            'product_bought':   'Product',
            'Total_Spend':      'Amount_Paid',
            'Total_Qty':        'Qty',
            'All_Order_Dates':  'All_Purchase_Dates',
            'Last_Order_Date':  'Purchase_Date',
        }
        web = web.rename(columns={k: v for k, v in col_map.items() if k in web.columns})
        if 'source' not in web.columns:
            web['source'] = 'Website Order'
        frames.append(web)

    # --- Social media items ---
    if not df_social.empty:
        soc = df_social.copy()
        # analytics tracks mentions not quantities — mark clearly
        if 'Qty' not in soc.columns:
            soc['Qty'] = None
        if 'All_Purchase_Dates' not in soc.columns and 'Purchase_Date' in soc.columns:
            soc['All_Purchase_Dates'] = soc['Purchase_Date'].astype(str)
        frames.append(soc)

    if not frames:
        print("      ⚠️  No product-level data available.")
        return pd.DataFrame()

    combined = pd.concat(frames, ignore_index=True)

    # Final column order
    final_cols = [
        'phone_clean', 'client_name', 'email',
        'source',
        'Product', 'Brand', 'Category', 'Sub_Category',
        'Qty', 'Amount_Paid',
        'Purchase_Date', 'All_Purchase_Dates',
        'Location',
    ]
    final_cols = [c for c in final_cols if c in combined.columns]
    combined = combined[final_cols].sort_values(
        ['phone_clean', 'Purchase_Date'],
        ascending=[True, False],
        na_position='last'
    )

    print(f"      ✅ Product-level sheet: {len(combined):,} rows across all channels")
    return combined


# ==========================================
# 5. BUILD UNIFIED CLIENT LIST (one row per person)
# ==========================================

def build_unified_client_list(df_online, df_pos, df_website):
    """
    Merges all three sources by phone number.
    Returns one row per unique client with spend breakdown and tiers.
    """
    print("\n   🔗 Building unified client list...")

    frames = []

    KEEP_COLS = [
        'phone_clean', 'client_name', 'email',
        'primary_source', 'channel_tier',
        'whatsapp_spend', 'pos_spend', 'website_spend',
        'Total_Orders', 'total_orders', 'Total_Transactions',
        'First_Visit', 'Last_Visit', 'First_Order', 'Last_Order',
        'first_seen', 'last_seen',
        'Products_Bought', 'Branches_Visited',
        'lifetime_tier', 'lifetime_bracket'
    ]

    for df in [df_online, df_pos, df_website]:
        if df.empty:
            continue
        available = [c for c in KEEP_COLS if c in df.columns]
        frames.append(df[available].copy())

    if not frames:
        print("      ❌ No data from any source.")
        return pd.DataFrame()

    stacked = pd.concat(frames, ignore_index=True)
    stacked = stacked[stacked['phone_clean'].notna() & (stacked['phone_clean'] != '')]

    # Ensure optional columns always exist so the agg guards work reliably
    for _col in ['Branches_Visited', 'Products_Bought', 'channel_tier',
                 'whatsapp_spend', 'pos_spend', 'website_spend']:
        if _col not in stacked.columns:
            stacked[_col] = None

    def first_valid(series):
        for val in series:
            if pd.notna(val) and str(val).strip() not in ('', 'Unknown', 'nan'):
                return val
        return None

    def pipe_join_unique(series):
        vals = series.dropna().astype(str).str.strip()
        vals = vals[vals != ''].unique()
        return ' | '.join(sorted(vals)) if len(vals) > 0 else None

    # Base aggregations — always present
    agg_rules = {
        'client_name':    ('client_name',    first_valid),
        'email':          ('email',          first_valid),
        'primary_source': ('primary_source', first_valid),
        'all_channels':   ('primary_source', pipe_join_unique),
        'whatsapp_spend': ('whatsapp_spend', 'sum'),
        'pos_spend':      ('pos_spend',      'sum'),
        'website_spend':  ('website_spend',  'sum'),
    }
    # Optional columns — only include if present after stacking
    if 'Branches_Visited' in stacked.columns:
        agg_rules['Branches_Visited'] = ('Branches_Visited', first_valid)
    if 'Products_Bought' in stacked.columns:
        agg_rules['Products_Bought']  = ('Products_Bought',  pipe_join_unique)

    agg = stacked.groupby('phone_clean', as_index=False).agg(**agg_rules)

    # Primary source = highest-spend channel
    def resolve_primary_source(row):
        candidates = {
            'WhatsApp':      row['whatsapp_spend'],
            'Website Order': row['website_spend'],
            'Walk-In':       row['pos_spend'],
        }
        return max(candidates, key=candidates.get)

    agg['primary_source'] = agg.apply(resolve_primary_source, axis=1)

    # Spend totals and tiers
    agg['combined_spend'] = agg['whatsapp_spend'] + agg['pos_spend'] + agg['website_spend']
    agg['combined_tier']  = agg['combined_spend'].apply(assign_tier)
    agg['whatsapp_tier']  = agg['whatsapp_spend'].apply(assign_tier)
    agg['pos_tier']       = agg['pos_spend'].apply(assign_tier)
    agg['website_tier']   = agg['website_spend'].apply(assign_tier)

    # Multi-channel flag
    channel_count = (
        (agg['whatsapp_spend'] > 0).astype(int) +
        (agg['pos_spend']      > 0).astype(int) +
        (agg['website_spend']  > 0).astype(int)
    )
    agg['is_multichannel'] = (channel_count > 1).map({True: 'Yes', False: 'No'})

    final_cols = [
        'phone_clean', 'client_name', 'email',
        'primary_source', 'all_channels', 'is_multichannel',
        'combined_tier',  'combined_spend',
        'whatsapp_spend', 'whatsapp_tier',
        'pos_spend',      'pos_tier',
        'website_spend',  'website_tier',
        'Branches_Visited', 'Products_Bought',
    ]
    final_cols = [c for c in final_cols if c in agg.columns]
    agg = agg[final_cols].sort_values('combined_spend', ascending=False)

    print(f"      ✅ Unified list: {len(agg):,} unique clients")
    print(f"      🔀 Multi-channel clients: {(agg['is_multichannel'] == 'Yes').sum():,}")

    return agg


# ==========================================
# 6. MAIN EXPORT
# ==========================================

def run_client_export():
    print("\n" + "="*60)
    print("📋 PORTAL CLIENT LIST EXPORT")
    print("="*60)

    os.makedirs(OUTPUT_PATH.parent, exist_ok=True)

    # ── 1. Connect to DB ─────────────────────────────────────────
    engine = None
    try:
        from sqlalchemy import create_engine, text
        engine = create_engine(DB_CONNECTION_STRING)
        engine.connect()
        print("   🐘 DB connection OK")
    except Exception as e:
        print(f"   ⚠️  DB unavailable: {e}")
        engine = None

    # ── 2. Client summary from mv_client_list ────────────────────
    df_clients = pd.DataFrame()
    if engine is not None:
        try:
            df_clients = pd.read_sql("SELECT * FROM mv_client_list", engine)
            df_clients = df_clients.rename(columns={
                'phone_number':           'Phone',
                'client_name':            'Client Name',
                'preferred_location':     'Preferred Branch',
                'branches_visited':       'Branches Visited',
                'products_bought':        'Products Bought',
                'first_interaction_date': 'First Purchase',
                'last_interaction_date':  'Last Purchase',
                'total_lifetime_spend':   'Total Spend (KES)',
                'total_purchases':        'Total Transactions',
                'lifetime_tier':          'Tier',
                'name_audit_flag':        'Name Audit',
            })
            df_clients['Source'] = 'Physical / POS'
            print(f"   ✅ {len(df_clients):,} clients loaded")
        except Exception as e:
            print(f"   ❌ mv_client_list failed: {e}")

    # ── 3. Purchase history — one row per line item per transaction ──
    # Shows the actual transaction date and a visit number (1st, 2nd, 27th visit)
    # so you can see exactly when each item was bought and in which visit
    df_products = pd.DataFrame()
    if engine is not None:
        try:
            _product_sql = text("""
                WITH visit_numbers AS (
                    -- Assign a chronological visit number per client
                    -- based on distinct transaction dates
                    SELECT
                        phone_number,
                        transaction_id,
                        DENSE_RANK() OVER (
                            PARTITION BY phone_number
                            ORDER BY MIN(sale_date)
                        ) AS visit_number
                    FROM fact_sales_lineitems
                    WHERE phone_number IS NOT NULL
                      AND TRIM(phone_number) <> ''
                    GROUP BY phone_number, transaction_id
                )
                SELECT
                    f.phone_number                          AS "Phone",
                    f.client_name                           AS "Client Name",
                    f.location                              AS "Branch",
                    f.sale_date                             AS "Date",
                    v.visit_number                          AS "Visit No.",
                    f.transaction_id                        AS "Transaction ID",
                    f.description                           AS "Product",
                    f.category                              AS "Category",
                    f.department                            AS "Department",
                    f.qty_sold                              AS "Qty",
                    f.total_tax_ex                          AS "Amount (KES)",
                    CASE
                        WHEN f.ordered_via ILIKE '%whatsapp%'
                          OR f.ordered_via ILIKE '%respond%'
                        THEN 'Online / Social Media'
                        ELSE 'Physical / POS'
                    END                                     AS "Source"
                FROM fact_sales_lineitems f
                JOIN visit_numbers v
                  ON f.phone_number    = v.phone_number
                 AND f.transaction_id  = v.transaction_id
                WHERE f.phone_number IS NOT NULL
                  AND TRIM(f.phone_number) <> ''
                  AND f.description IS NOT NULL
                ORDER BY
                    f.phone_number,
                    f.sale_date DESC,
                    v.visit_number DESC,
                    f.description
            """)
            df_products = pd.read_sql(_product_sql, engine)
            print(f"   ✅ {len(df_products):,} purchase history rows loaded")
        except Exception as e:
            print(f"   ⚠️  Product detail failed: {e}")

    # ── 4. Website clients ───────────────────────────────────────
    df_website, df_website_items = load_website_clients()
    if not df_website.empty:
        df_website['Source'] = 'Website'
    if not df_website_items.empty:
        df_website_items['Source'] = 'Website'

    # ── 5. Tier splits ───────────────────────────────────────────
    if df_clients.empty:
        print("\n❌ No client data to export.")
        return

    def split_tier(df, tier):
        return df[df['Tier'] == tier].copy() if 'Tier' in df.columns else pd.DataFrame()

    platinum = split_tier(df_clients, 'Platinum')
    gold     = split_tier(df_clients, 'Gold')
    silver   = split_tier(df_clients, 'Silver')
    bronze   = split_tier(df_clients, 'Bronze')

    print(f"\n   💎 Platinum  : {len(platinum):,}")
    print(f"   🥇 Gold      : {len(gold):,}")
    print(f"   🥈 Silver    : {len(silver):,}")
    print(f"   🥉 Bronze    : {len(bronze):,}")
    print(f"   👥 Total     : {len(df_clients):,}")
    print(f"   📦 Products  : {len(df_products):,}")

    # ── 6. Write Excel ───────────────────────────────────────────
    print("\n   💾 Writing Excel...")
    try:
        dfs_to_clean = [df_clients, platinum, gold, silver, bronze,
                        df_products, df_website, df_website_items]
        df_clients, platinum, gold, silver, bronze, df_products, df_website, df_website_items = (
            sanitize_for_excel(d) if not d.empty else d for d in dfs_to_clean
        )

        with pd.ExcelWriter(OUTPUT_PATH, engine='openpyxl') as writer:

            # All clients summary
            df_clients.to_excel(writer, sheet_name='All Clients', index=False)

            # Product detail — what each client bought, when, how many
            if not df_products.empty:
                df_products.to_excel(writer, sheet_name='Purchase History', index=False)

            # Tier sheets
            platinum.to_excel(writer, sheet_name='Platinum', index=False)
            gold.to_excel(writer,     sheet_name='Gold',     index=False)
            silver.to_excel(writer,   sheet_name='Silver',   index=False)
            bronze.to_excel(writer,   sheet_name='Bronze',   index=False)

            # Website
            if not df_website.empty:
                df_website.to_excel(writer, sheet_name='Website Clients', index=False)
            if not df_website_items.empty:
                df_website_items.to_excel(writer, sheet_name='Website Purchases', index=False)

        print(f"\n✅ CLIENT LIST SAVED: {OUTPUT_PATH.name}")
        print("   Sheets:")
        print("      All Clients     — one row per client, total spend + tier")
        print("      Purchase History — one row per client × product, qty + dates + source")
        print("      Platinum / Gold / Silver / Bronze — tier splits")
        print("      Website Clients / Website Purchases")

    except Exception as e:
        print(f"   ❌ Excel export failed: {e}")
        raise

    finally:
        if engine:
            engine.dispose()



if __name__ == "__main__":
    run_client_export()