UPDATE dim_product_catalogue SET department = 'Cosmetics'              WHERE UPPER(TRIM(department)) = 'COSMETICS';
UPDATE dim_product_catalogue SET department = 'Skincare'               WHERE UPPER(TRIM(department)) IN ('SKINCARE','SKIN CARE PRODUCTS','SKIN CARE');
UPDATE dim_product_catalogue SET department = 'Supplements'            WHERE UPPER(TRIM(department)) = 'SUPPLEMENTS';
UPDATE dim_product_catalogue SET department = 'General Prescription'   WHERE UPPER(TRIM(department)) IN ('GENERAL PRESCRIPTIONS','GENERAL PRESCRIPTION');
UPDATE dim_product_catalogue SET department = 'Baby Care'              WHERE UPPER(TRIM(department)) IN ('BABYCARE','BABY CARE');
UPDATE dim_product_catalogue SET department = 'Oral Care'              WHERE UPPER(TRIM(department)) IN ('ORAL CARE','0RAL CARE');
UPDATE dim_product_catalogue SET department = 'Lip Care'               WHERE UPPER(TRIM(department)) IN ('LIP CARE','LIPCARE');
UPDATE dim_product_catalogue SET department = 'Hair Care'              WHERE UPPER(TRIM(department)) IN ('HAIR CARE','HAIRCARE PRODUCTS');
UPDATE dim_product_catalogue SET department = 'Medical Devices & Kits' WHERE UPPER(TRIM(department)) IN ('MEDICAL DEVICES &  KITS','MEDICAL DEVICES AND KITS');
UPDATE dim_product_catalogue SET department = 'Feminine Care'          WHERE UPPER(TRIM(department)) IN ('FEMININE','FEMININE CARE');
UPDATE dim_product_catalogue SET department = 'Perfumes'               WHERE UPPER(TRIM(department)) = 'PERFUMES';
UPDATE dim_product_catalogue SET department = 'Antibiotics'            WHERE UPPER(TRIM(department)) = 'ANTIBIOTICS';
UPDATE dim_product_catalogue SET department = 'Vaccines'               WHERE UPPER(TRIM(department)) = 'VACCINES';
UPDATE dim_product_catalogue SET department = 'Jewellery'              WHERE UPPER(TRIM(department)) = 'JEWELLERY';
UPDATE dim_product_catalogue SET department = 'Wholesale'              WHERE UPPER(TRIM(department)) = 'WHOLESALE';
UPDATE dim_product_catalogue SET department = 'OTC'                    WHERE UPPER(TRIM(department)) = 'O.T.C';
UPDATE dim_product_catalogue SET department = 'Medicine & Treatment'   WHERE UPPER(TRIM(department)) = 'MEDICINE &TREATMENT';
UPDATE dim_product_catalogue SET department = 'Homeopathy'             WHERE UPPER(TRIM(department)) = 'HOMEOPATHY';
UPDATE dim_product_catalogue SET department = 'Men Care'               WHERE UPPER(TRIM(department)) = 'MEN CARE';
UPDATE dim_product_catalogue SET department = 'First Aid'              WHERE UPPER(TRIM(department)) = 'FIRST AID';
UPDATE dim_product_catalogue SET department = 'Interbranch'            WHERE UPPER(TRIM(department)) = 'BRANCHES';
UPDATE dim_product_catalogue SET department = NULL                     WHERE TRIM(department) = 'BYOMA Foaming Rice clean 175m';
UPDATE dim_product_catalogue SET department = 'Cards & Airtime'        WHERE UPPER(TRIM(department)) IN ('CARDS-AIRTIME','CARDS - AIRTIME');